spring.application.name=url-shortener-sb

spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener
spring.datasource.username=urlapp
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MYSQLDialect

jwt.secret=4wBQlQB44XelXo8BRs4Y6LoqeDFUOUjDJxuF-R4eNKsf-ezwYVBK9nxIg9Mwjt2di7MJK5n3N_iNq9ODGViMJg
jwt.expiration=172800000